# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 448e85011424be24a58744dc298ba934a876e9bb287db5c99d83de46dfffe2758e5797ecb6895463e6d417b9383cee2c8b853605eb9bfeb91c009f6b1726ccc0

test:
  secret_key_base: 07e4d19dda457d799c3791e4fc50d6aa370dcdb2ee69fb034449a1073b0dc3dc283178aaae8b6fb542e2b3fa97253bc4523578b95e94e184169f2e0c646b652f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
